spring:
    application:
        name: document-uploader-service
    cloud:
        config:
            uri: optional:${CONFIG_SERVER_URL}
            fail-fast: true
            enabled: false
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB
    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                jdbc:
                    lob:
                        non_contextual_creation: true
            show-sql: false

server:
    port: 8092

eureka:
    client:
        service-url:
            defaultZone : http://localhost:8761/eureka/


# Fallback configuration in case Config Server is unavailable
azure:
    storage:
        connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
        container-name: documents
        base-url: ${AZURE_STORAGE_BASE_URL}

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html
        operationsSorter: method