spring:
  data:
    mongodb:
      username: StudySolution
      password: StudySolution
      host: localhost
      port: 27017
      database: user
      authentication-database: admin
      auto-index-creation: true

server:
  port: 8090